from typing import(
    Protocol,
    TypeVar,
    Type,
    Any,
    Optional,
    Self
)

from payments.domain.entities import (
    BaseEntitiy,
    Order,
    Payment,
    T_Domain_Entity,
)
from payments.domain.value_objects import(
    OrderId,
    PaymentId,
    BaseId,
    T_Domain_ID,
)



T_ORM_Model = TypeVar("T_ORM_Model")
T_Query = TypeVar("T_Query", bound="QueryProto")


class QueryProto(Protocol[T_ORM_Model]):
    def filter_by(self, **kwargs) -> Any: ...
    def filter(self, *criterion) -> Any: ...
    def first(self) -> Optional[T_ORM_Model]: ...
    def order_by(self: T_Query, *args: Any) -> T_Query: ...
    def limit(self: T_Query, number: int) -> T_Query: ...
    def offset(self: T_Query, number: int) -> T_Query: ...
    def all(self) -> list[T_ORM_Model]: ...
    def count(self) -> int: ...
    def subquery(self) -> Any: ...
    def desc(self: T_Query, *args: Any) -> T_Query: ...


class ORMSessionProto(Protocol[T_ORM_Model]):
    def add(self, instance: T_ORM_Model) -> None: ...
    def get(
            self,
            orm_model_cls: Type[T_ORM_Model],
            instance_id: Type[BaseId] | int | str
        ) -> Optional[T_ORM_Model]: ...
    def delete(self, instance: T_ORM_Model) -> None: ...
    def commit(self) -> None: ...
    def flush(self) -> None: ...
    def refresh(self, instance: T_ORM_Model) -> None: ...
    def rollback(self) -> None: ...
    def query(self, model_cl: Type[T_ORM_Model]) -> QueryProto[T_ORM_Model]: ...
    def close(self) -> None: ...


class RepoProto(Protocol[T_Domain_Entity, T_ORM_Model, T_Domain_ID]):
    entity_cls: type[T_Domain_Entity]
    orm_model_cls: type[T_ORM_Model]

    def entity_to_model(self) -> T_ORM_Model: ...
    def model_to_entity(self) -> T_Domain_Entity: ...
    def add(self, instance: T_Domain_Entity) -> None: ...
    def get_by_id(self, instance_id: T_Domain_ID) -> Optional[T_Domain_Entity]: ...
    def delete(self, instance: T_Domain_Entity) -> None: ...
    def query(self) -> QueryProto[T_Domain_Entity]: ...


class OrderRepoProto(RepoProto[Order, T_ORM_Model, OrderId]): ...


class PaymentRepoProto(RepoProto[Payment, T_ORM_Model, PaymentId]): ...


# class OrderRepoProto(Protocol):
#     model_cls: Order

#     def add(self, instance: Order) -> None: ...
#     def get_by_id(self, instance_id: str) -> Optional[Order]: ...
#     def delete(self, instance: Order) -> None: ...
#     def attach_session(self, session: ORMSessionProto[Order]) -> None: ...
#     def query(self) -> QueryProto[Order]: ...


# class PaymentRepoProto(Protocol):
#     model_cls: Payment
#     def add_to_orm_session(self, instance: Payment) -> None: ...
#     def get_by_id(self, instance_id: str) -> Optional[Payment]: ...
#     def delete(self, instance: Payment) -> None: ...
#     def attach_session(self, session: ORMSessionProto[Payment]) -> None: ...
#     def query(self) -> QueryProto[Payment]: ...


class UoWProto(Protocol):
    orders: OrderRepoProto
    payments: PaymentRepoProto

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def commit(self) -> None: ...
    def flush(self) -> None: ...
    def refresh(self, instance: Order | Payment) -> None: ...
    def rollback(self) -> None: ...
