from typing import(
    Protocol,
    TypeVar,
    Type,
    Any,
    Optional,
    Self
)

from payments.domain.entities import (
    Order,
    Payment
)
from payments.domain.value_objects import(
    OrderId,
    PaymentId,
    BaseId,
)



TEntity = TypeVar("TEntity")
Q = TypeVar("Q", bound="QueryProto")


class QueryProto(Protocol[TEntity]):
    def filter_by(self, **kwargs) -> Any: ...
    def filter(self, *criterion) -> Any: ...
    def first(self) -> Optional[TEntity]: ...
    def order_by(self: Q, *args: Any) -> Q: ...
    def limit(self: Q, number: int) -> Q: ...
    def offset(self: Q, number: int) -> Q: ...
    def all(self) -> list[TEntity]: ...
    def count(self) -> int: ...
    def subquery(self) -> Any: ...
    def desc(self: Q, *args: Any) -> Q: ...


class ORMSessionProto(Protocol[TEntity]):
    def add(self, instance: TEntity) -> None: ...
    def get(
            self,
            model_cls: Type[TEntity],
            instance_id: Type[OrderId] | Type[PaymentId] | int
    ) -> Optional[TEntity]: ...
    def delete(self, instance: TEntity) -> None: ...
    def commit(self) -> None: ...
    def flush(self) -> None: ...
    def refresh(self, instance: TEntity) -> None: ...
    def rollback(self) -> None: ...
    def query(self, model_cl: Type[TEntity]) -> QueryProto: ...
    def close(self) -> None: ...


class OrderRepoProto(Protocol):
    model_cls: Order

    def add(self, instance: Order) -> None: ...
    def get_by_db_id(self, instance_id: str) -> Optional[Order]: ...
    def delete(self, instance: Order) -> None: ...
    def attach_session(self, session: ORMSessionProto[Order]) -> None: ...
    def query(self) -> QueryProto[Order]: ...


class PaymentRepoProto(Protocol):
    model_cls: Payment
    def add(self, instance: Payment) -> None: ...
    def get_by_db_id(self, instance_id: str) -> Optional[Payment]: ...
    def delete(self, instance: Payment) -> None: ...
    def attach_session(self, session: ORMSessionProto[Payment]) -> None: ...
    def query(self) -> QueryProto[Payment]: ...


class UoWProto(Protocol):
    orders: OrderRepoProto
    payments: PaymentRepoProto

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def commit(self) -> None: ...
    def flush(self) -> None: ...
    def refresh(self, instance: Order | Payment) -> None: ...
    def rollback(self) -> None: ...
