from typing import(
    Protocol,
    TypeVar,
    Type,
    Any,
    Optional,
    Self
)

from payments.domain.entities import (
    BaseEntity,
    Order,
    Payment
)


Entity = TypeVar("Entity", bound=BaseEntity)
Tid = TypeVar("Tid")
Q = TypeVar("Q", bound="QueryProto")
TRepoProto = TypeVar("TRepoProto", bound="RepoProtoBase")


class QueryProto(Protocol[Entity]):
    def filter_by(self, **kwargs) -> Any: ...
    def filter(self, *criterion) -> Any: ...
    def first(self) -> Optional[Entity]: ...
    def order_by(self: Q, *args: Any) -> Q: ...
    def limit(self: Q, number: int) -> Q: ...
    def offset(self: Q, number: int) -> Q: ...
    def all(self) -> list[Entity]: ...
    def count(self) -> int: ...
    def subquery(self) -> Any: ...
    def desc(self: Q, *args: Any) -> Q: ...


class ORMSessionProto(Protocol[Entity]):
    def add(self, instance: Entity) -> None: ...
    def get(self, model_cls: Type[Entity], instance_id: Tid) -> Optional[Entity]: ...
    def delete(self, instance: Entity) -> None: ...
    def commit(self) -> None: ...
    def flush(self) -> None: ...
    def refresh(self, instance: Entity) -> None: ...
    def rollback(self) -> None: ...
    def query(self, model_cl: Type[Entity]) -> QueryProto: ...
    def close(self) -> None: ...


class RepoProtoBase(Protocol[Entity, Tid]):
    model_cls: Type[Entity]

    def add(self, instance: Entity) -> None: ...
    def get_by_db_id(self, instance_id: Tid) -> Entity | None: ...
    def delete(self, instance: Entity) -> None: ...
    def attach_session(self, session: ORMSessionProto[Entity]) -> None: ...
    def query(self) -> QueryProto[Entity]: ...


class OrderRepoProto(RepoProtoBase[Order, Tid]): ...


class PaymentRepoProto(RepoProtoBase[Order, Tid]): ...


class UoWProto(Protocol[Entity, Tid, TRepoProto]):
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def commit(self) -> None: ...
    def flush(self) -> None: ...
    def refresh(self, instance: Entity) -> None: ...
    def rollback(self) -> None: ...
    def __getattr__(self, item) -> TRepoProto: ...
