from payments.domain.entities.payment import Payment
from payments.domain.entities.order import Order
from payments.domain.repos_interfaces import (
    OrderRepoProto,
    PaymentRepoProto
)

from typing import (
    Any,
    Protocol,
    Self,
    Type,
    TypeVar,
    Optional,
)

from payments.domain.value_objects import BaseId



T_ORM_Model = TypeVar("T_ORM_Model")


class UoWProto(Protocol):
    orders: OrderRepoProto
    payments: PaymentRepoProto

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def commit(self) -> None: ...
    def flush(self) -> None: ...
    def refresh(self, instance: Order | Payment) -> None: ...
    def rollback(self) -> None: ...


class QueryProto(Protocol[T_ORM_Model]):
    def filter_by(self, **kwargs) -> Any: ...
    def filter(self, *criterion) -> Any: ...
    def first(self) -> Optional[T_ORM_Model]: ...
    def order_by(self, *args: Any) -> Self: ...
    def limit(self, number: int) -> Self: ...
    def offset(self, number: int) -> Self: ...
    def all(self) -> list[T_ORM_Model]: ...
    def count(self) -> int: ...
    def subquery(self) -> Any: ...
    def desc(self, *args: Any) -> Self: ...


class ORMSessionProto(Protocol[T_ORM_Model]):
    def add(self, instance: T_ORM_Model) -> None: ...
    def get(
            self,
            orm_model_cls: Type[T_ORM_Model],
            instance_id: Type[BaseId] | int | str
        ) -> Optional[T_ORM_Model]: ...
    def delete(self, instance: T_ORM_Model) -> None: ...
    def commit(self) -> None: ...
    def flush(self) -> None: ...
    def refresh(self, instance: T_ORM_Model) -> None: ...
    def rollback(self) -> None: ...
    def query(self, model_cl: Type[T_ORM_Model]) -> QueryProto[T_ORM_Model]: ...
    def close(self) -> None: ...
